.TH GAMINGGEARFXCONTROL "1" "November 2017" "gaminggearfxcontrol version 0.15.1" "User Commands"
.SH NAME
gaminggearfxcontrol \- Control gaminggear fx
.SH DESCRIPTION
.SS "Usage:"
.IP
gaminggearfxcontrol [OPTION?] \- control Gaminggear FX
.SS "Help Options:"
.TP
\fB\-h\fR, \fB\-\-help\fR
Show help options
.SS "Application Options:"
.TP
\fB\-d\fR, \fB\-\-device\fR=\fI\,STRING\/\fR
use device STRING
.TP
\fB\-l\fR, \fB\-\-light\fR=\fI\,INDEX\/\fR
use light index INDEX
.TP
\fB\-a\fR, \fB\-\-all\fR
set all colors
.TP
\fB\-s\fR, \fB\-\-single\fR
set single color
.TP
\fB\-r\fR, \fB\-\-reset\fR
reset colors
.TP
\fB\-c\fR, \fB\-\-color\fR
set plain color
.TP
\fB\-1\fR, \fB\-\-color1\fR=\fI\,COLOR1\/\fR
COLOR1
